name: Deploy to DigitalOcean Droplet

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 138.68.124.92 >> ~/.ssh/known_hosts

    - name: Deploy to Droplet
      run: |
        ssh -o StrictHostKeyChecking=no root@138.68.124.92 << 'ENDSSH'
          cd /var/www/tyche
          rm -r Tyche
          git clone git@github.com:Ramphy0x90/Tyche.git
          cat init
          ./init
          docker image prune -f
          docker stop tychesvr
          docker rm tychesvr
          docker run -d -p 127.0.0.1:8080:8080 --network bridge --name tychesvr tyche
        ENDSSH
